# 공통(기본 프로파일 : local)
spring:
  profiles:
    active: local
  datasource:
    initialization-mode: always
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000

---
# test 프로파일
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true

---
# local 프로파일
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/subway_local?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: air
    password: air

---
# prod 프로파일
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.14:3306/subway?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: air
    password: 1234
    